config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/contact'
  get 'welcome/faq'
  get 'welcome/pricing'
  get 'welcome/features'

  resources :invoices
  
  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[ show edit update destroy ]

  # GET /invoices or /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1 or /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:date, :company, :tax, :salesperson)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def faq
  end

  def pricing
  end

  def features
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice) do |form| %>
  <% if invoice.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.datetime_field :date %>
  </div>

  <div>
    <%= form.label :company, style: "display: block" %>
    <%= form.text_field :company %>
  </div>

  <div>
    <%= form.label :tax, style: "display: block" %>
    <%= form.text_field :tax %>
  </div>

  <div>
    <%= form.label :salesperson, style: "display: block" %>
    <%= form.text_field :salesperson %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/_invoice.html.erb
<div id="<%= dom_id invoice %>">
  <p>
    <strong>Date:</strong>
    <%= invoice.date %>
  </p>

  <p>
    <strong>Company:</strong>
    <%= invoice.company %>
  </p>

  <p>
    <strong>Tax:</strong>
    <%= invoice.tax %>
  </p>

  <p>
    <strong>Salesperson:</strong>
    <%= invoice.salesperson %>
  </p>

</div>

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>

<%= render "form", invoice: @invoice %>

<br>

<div>
  <%= link_to "Show this invoice", @invoice %> |
  <%= link_to "Back to invoices", invoices_path %>
</div>

app/views/invoices/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Invoices</h1>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">  

<div id="invoices">
  <% @invoices.each do |invoice| %>
    <%= render invoice %>
    <p>
      <%= link_to "Show this invoice", invoice %>
    </p>
  <% end %>
</div>

<%= link_to "New invoice", new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<%= render "form", invoice: @invoice %>

<br>

<div>
  <%= link_to "Back to invoices", invoices_path %>
</div>

app/views/invoices/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @invoice %>

<div>
  <%= link_to "Edit this invoice", edit_invoice_path(@invoice) %> |
  <%= link_to "Back to invoices", invoices_path %>

  <%= button_to "Destroy this invoice", @invoice, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Charger</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "HOME", root_path %></li>
      <li><%= link_to "About Us", welcome_about_path %></li>
      <li><%= link_to "Contact", welcome_contact_path %></li>
      <li><%= link_to "Features", welcome_features_path %></li>
      <li><%= link_to "FAQs", welcome_faq_path %></li>
      <li><%= link_to "Pricing", welcome_pricing_path %></li>
      <li><%= link_to "Invoices", invoices_path %></li>
      <li><%= link_to "Login", root_path %></li>
    </ul>
    <%= yield %>
  </div>  
  </body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me anywhere</p>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/faq.html.erb
<h1>Welcome#faq</h1>
<p>Find me in app/views/welcome/faq.html.erb</p>

app/views/welcome/features.html.erb
<h1>Welcome#features</h1>
<p>Find me in app/views/welcome/features.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/pricing.html.erb
<h1>Welcome#pricing</h1>
<p>Find me in app/views/welcome/pricing.html.erb</p>